server:
  port: 8084
spring:
  application:
    name: ly-page
  thymeleaf:
    cache: false

  rabbitmq:
    host: 192.168.220.128
    username: guest
    password: guest
    virtual-host: /


eureka:
      client:
        service-url:
          defaultZone: http://127.0.0.1:10086/eureka