server:
  port: 8085
spring:
  application:
    name: ly-user-service
  datasource:
    url: jdbc:mysql:///leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.220.129 #服务器地址
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 192.168.220.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.leyou.user.pojo

#自定义的配置文件
ly:
  user:
    exchangeName: ly.sms.exchange
    routingKey: sms.verity.code
    timeOut: 10 #验证码在redis中保存的时长 分钟

