server:
  port: 8081
spring:
  application:
    name: ly-ltem-service
  datasource:
    password: root
    username: root
    url: jdbc:mysql:///leyou
   # driver-class-name: com.mysql.jdbc.Driver可以不写

  rabbitmq:
    host: 192.168.220.129 #服务器地址
    username: guest
    password: guest
    virtual-host: /
    template:
      exchange: ly.item.exchange
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
    publisher-confirms: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#日志处理
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
